[".config/zsh/plugins/per-directory-history"]
    type = "archive"
    url = "https://github.com/jimhester/per-directory-history/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"
