# The omz version of this plugin has some fixes applied that are not present in
# the jimhester/per-directory-history repository.
# This is up-to-date as of 4/18/2024
[".config/zsh/per-directory-history.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/d17ca487a4/plugins/per-directory-history/per-directory-history.zsh"
